//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.TransactionDetails = new HashSet<TransactionDetails>();
        }
    
        public int Id { get; set; }
        public string ItemName { get; set; }
        public decimal UnitCost { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> UnitMeasureId { get; set; }
        public Nullable<bool> IsIncludedSurcharge { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDetails> TransactionDetails { get; set; }
        public virtual UnitMeasurements UnitMeasurements { get; set; }
    }
}
