//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelDb : DbContext
    {
        public ModelDb()
            : base("name=ModelDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<Permitees> Permitees { get; set; }
        public virtual DbSet<PermiteeTypes> PermiteeTypes { get; set; }
        public virtual DbSet<UserClaims> UserClaims { get; set; }
        public virtual DbSet<UserLogins> UserLogins { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vehicles> Vehicles { get; set; }
        public virtual DbSet<TransactionVehicles> TransactionVehicles { get; set; }
        public virtual DbSet<TransactionFacilities> TransactionFacilities { get; set; }
        public virtual DbSet<Facilities> Facilities { get; set; }
        public virtual DbSet<VehicleTypes> VehicleTypes { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<UserRolesInActions> UserRolesInActions { get; set; }
        public virtual DbSet<TransactionTypes> TransactionTypes { get; set; }
        public virtual DbSet<Particulars> Particulars { get; set; }
        public virtual DbSet<SummaryProgramOfWorks> SummaryProgramOfWorks { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<TransactionPenalties> TransactionPenalties { get; set; }
        public virtual DbSet<Barangays> Barangays { get; set; }
        public virtual DbSet<ProgramOfWorks> ProgramOfWorks { get; set; }
        public virtual DbSet<Quarries> Quarries { get; set; }
        public virtual DbSet<QuarriesInTransactions> QuarriesInTransactions { get; set; }
        public virtual DbSet<Hauleds> Hauleds { get; set; }
        public virtual DbSet<TransactionDetails> TransactionDetails { get; set; }
        public virtual DbSet<Signatories> Signatories { get; set; }
        public virtual DbSet<Actions> Actions { get; set; }
        public virtual DbSet<Productions> Productions { get; set; }
        public virtual DbSet<Provinces> Provinces { get; set; }
        public virtual DbSet<Towns> Towns { get; set; }
        public virtual DbSet<TransactionSags> TransactionSags { get; set; }
        public virtual DbSet<UnitMeasurements> UnitMeasurements { get; set; }
        public virtual DbSet<Sags> Sags { get; set; }
        public virtual DbSet<Transactions> Transactions { get; set; }
        public virtual DbSet<Billings> Billings { get; set; }
        public virtual DbSet<DeliveryReceipts> DeliveryReceipts { get; set; }
    }
}
