//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuarriesInTransactions
    {
        public int Id { get; set; }
        public int QuarryId { get; set; }
        public string TransactionId { get; set; }
        public int Percentage { get; set; }
        public Nullable<int> SagId { get; set; }
    
        public virtual Quarries Quarries { get; set; }
        public virtual Sags Sags { get; set; }
        public virtual Transactions Transactions { get; set; }
    }
}
