//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SummaryProgramOfWorks
    {
        public int Id { get; set; }
        public Nullable<int> ParticularId { get; set; }
        public Nullable<int> SagId { get; set; }
        public Nullable<int> ProgramOfWorkId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Particulars Particulars { get; set; }
        public virtual ProgramOfWorks ProgramOfWorks { get; set; }
        public virtual Sags Sags { get; set; }
    }
}
