//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionSags
    {
        public int Id { get; set; }
        public string TransactionId { get; set; }
        public Nullable<int> SagId { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
    
        public virtual Sags Sags { get; set; }
        public virtual Transactions Transactions { get; set; }
    }
}
