//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetails
    {
        public int Id { get; set; }
        public string TransactionId { get; set; }
        public int ItemId { get; set; }
        public int Quantity { get; set; }
        public decimal UnitCost { get; set; }
        public string EntryBy { get; set; }
        public string LastEditedBy { get; set; }
        public string Remarks { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Transactions Transactions { get; set; }
    }
}
