//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicles()
        {
            this.TransactionVehicles = new HashSet<TransactionVehicles>();
            this.Facilities = new HashSet<Facilities>();
            this.Productions = new HashSet<Productions>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PermiteeId { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
        public string PlateNo { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
    
        public virtual Permitees Permitees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionVehicles> TransactionVehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facilities> Facilities { get; set; }
        public virtual VehicleTypes VehicleTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Productions> Productions { get; set; }
    }
}
